### ISSUE TITLE
`500` error on persons properties endpoint

### ISSUE THREAD

**Issue by corywatilo** [PostHog/sidecar#9]
![2023-04-18 00 00 08](https://user-images.githubusercontent.com/154479/232669269-60509030-d783-4fc4-ac3f-2eab9591e8fc.gif)

![2023-04-18 00 00 08](https://user-images.githubusercontent.com/154479/232669450-a66dad63-f2cb-4023-8734-64b3db406419.gif)

**Comment by pjhul** [comment]
Fixed in aecb20dc201147a5cab3a3861c87b19e0f987e89
